config/routes.rb
Rails.application.routes.draw do
  resources :enderecos
  resources :estados
  resources :cidades
  resources :movimentode_estoques
  resources :operacaos
  resources :produtos
  resources :unidades
  resources :grupode_produtos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unidade.rb
class Unidade < ApplicationRecord

    validates :descricao, :sigla, presence: true
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]

  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1
  # PATCH/PUT /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade.destroy
    respond_to do |format|
      format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidade_params
      params.require(:unidade).permit(:descricao, :sigla)
    end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= form_with(model: unidade, local: true) do |form| %>
  <% if unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unidade.errors.count, "error") %> prohibited this unidade from being saved:</h2>

      <ul>
      <% unidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unidades/edit.html.erb
<h1>Editing Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Show', @unidade %> |
<%= link_to 'Back', unidades_path %>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Sigla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.descricao %></td>
        <td><%= unidade.sigla %></td>
        <td><%= link_to 'Show', unidade %></td>
        <td><%= link_to 'Edit', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Destroy', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unidade', new_unidade_path %>

app/views/unidades/new.html.erb
<h1>New Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Back', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @unidade.descricao %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @unidade.sigla %>
</p>

<%= link_to 'Edit', edit_unidade_path(@unidade) %> |
<%= link_to 'Back', unidades_path %>