config/routes.rb
Rails.application.routes.draw do
  resources :enderecos
  resources :estados
  resources :cidades
  resources :movimentode_estoques
  resources :operacaos
  resources :produtos
  resources :unidades
  resources :grupode_produtos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movimentode_estoque.rb
class MovimentodeEstoque < ApplicationRecord
    belongs_to :pessoa
    belongs_to :operacao
    belongs_to :produto

    validates :data, :quantidade, presence: true
    validates :quantidade, numericality: { greater_than_or_equal_to: 1,
                                       less_than_or_equal_to: 8 }
                                       
    scope :por_operacao, lambda { |produto, data, operacao|
        where('produto_id = ? and data <= ? and operacao_id = ?', produto, data, operacao).sum(:quantidade)
    }
end 

app/controllers/movimentode_estoques_controller.rb
class MovimentodeEstoquesController < ApplicationController
  before_action :set_movimentode_estoque, only: [:show, :edit, :update, :destroy]

  # GET /movimentode_estoques
  # GET /movimentode_estoques.json
  def index
    @movimentode_estoques = MovimentodeEstoque.all
  end

  # GET /movimentode_estoques/1
  # GET /movimentode_estoques/1.json
  def show
  end

  # GET /movimentode_estoques/new
  def new
    @movimentode_estoque = MovimentodeEstoque.new
  end

  # GET /movimentode_estoques/1/edit
  def edit
  end

  # POST /movimentode_estoques
  # POST /movimentode_estoques.json
  def create
    @movimentode_estoque = MovimentodeEstoque.new(movimentode_estoque_params)

    respond_to do |format|
      if @movimentode_estoque.save
        format.html { redirect_to @movimentode_estoque, notice: 'Movimentode estoque was successfully created.' }
        format.json { render :show, status: :created, location: @movimentode_estoque }
      else
        format.html { render :new }
        format.json { render json: @movimentode_estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimentode_estoques/1
  # PATCH/PUT /movimentode_estoques/1.json
  def update
    respond_to do |format|
      if @movimentode_estoque.update(movimentode_estoque_params)
        format.html { redirect_to @movimentode_estoque, notice: 'Movimentode estoque was successfully updated.' }
        format.json { render :show, status: :ok, location: @movimentode_estoque }
      else
        format.html { render :edit }
        format.json { render json: @movimentode_estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimentode_estoques/1
  # DELETE /movimentode_estoques/1.json
  def destroy
    @movimentode_estoque.destroy
    respond_to do |format|
      format.html { redirect_to movimentode_estoques_url, notice: 'Movimentode estoque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimentode_estoque
      @movimentode_estoque = MovimentodeEstoque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimentode_estoque_params
      params.require(:movimentode_estoque).permit(:data, :quantidade, :pessoa, :operacao, :produto)
    end
end

app/helpers/movimentode_estoques_helper.rb
module MovimentodeEstoquesHelper
end

app/views/movimentode_estoques/_form.html.erb
<%= form_with(model: movimentode_estoque, local: true) do |form| %>
  <% if movimentode_estoque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movimentode_estoque.errors.count, "error") %> prohibited this movimentode_estoque from being saved:</h2>

      <ul>
      <% movimentode_estoque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :pessoa %>
    <%= form.text_field :pessoa %>
  </div>

  <div class="field">
    <%= form.label :operacao %>
    <%= form.text_field :operacao %>
  </div>

  <div class="field">
    <%= form.label :produto %>
    <%= form.text_field :produto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movimentode_estoques/edit.html.erb
<h1>Editing Movimentode Estoque</h1>

<%= render 'form', movimentode_estoque: @movimentode_estoque %>

<%= link_to 'Show', @movimentode_estoque %> |
<%= link_to 'Back', movimentode_estoques_path %>

app/views/movimentode_estoques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movimentode Estoques</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Quantidade</th>
      <th>Pessoa</th>
      <th>Operacao</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movimentode_estoques.each do |movimentode_estoque| %>
      <tr>
        <td><%= movimentode_estoque.data %></td>
        <td><%= movimentode_estoque.quantidade %></td>
        <td><%= movimentode_estoque.pessoa %></td>
        <td><%= movimentode_estoque.operacao %></td>
        <td><%= movimentode_estoque.produto %></td>
        <td><%= link_to 'Show', movimentode_estoque %></td>
        <td><%= link_to 'Edit', edit_movimentode_estoque_path(movimentode_estoque) %></td>
        <td><%= link_to 'Destroy', movimentode_estoque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movimentode Estoque', new_movimentode_estoque_path %>

app/views/movimentode_estoques/new.html.erb
<h1>New Movimentode Estoque</h1>

<%= render 'form', movimentode_estoque: @movimentode_estoque %>

<%= link_to 'Back', movimentode_estoques_path %>

app/views/movimentode_estoques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @movimentode_estoque.data %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @movimentode_estoque.quantidade %>
</p>

<p>
  <strong>Pessoa:</strong>
  <%= @movimentode_estoque.pessoa %>
</p>

<p>
  <strong>Operacao:</strong>
  <%= @movimentode_estoque.operacao %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @movimentode_estoque.produto %>
</p>

<%= link_to 'Edit', edit_movimentode_estoque_path(@movimentode_estoque) %> |
<%= link_to 'Back', movimentode_estoques_path %>