config/routes.rb
Rails.application.routes.draw do
  resources :enderecos
  resources :estados
  resources :cidades
  resources :movimentode_estoques
  resources :operacaos
  resources :produtos
  resources :unidades
  resources :grupode_produtos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cidade.rb
class Cidade < ApplicationRecord
    belongs_to :estado

    validates :nome, :cep, :bairro, presence: true
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:nome, :cep, :bairro)
    end
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/views/cidades/_form.html.erb
<%= form_with(model: cidade, local: true) do |form| %>
  <% if cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cep</th>
      <th>Bairro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cidades.each do |cidade| %>
      <tr>
        <td><%= cidade.nome %></td>
        <td><%= cidade.cep %></td>
        <td><%= cidade.bairro %></td>
        <td><%= link_to 'Show', cidade %></td>
        <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
        <td><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cidade', new_cidade_path %>

app/views/cidades/new.html.erb
<h1>New Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @cidade.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cidade.bairro %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>